service: app
provider:
    name: aws
    region: us-east-1
    runtime: provided
    iamRoleStatements:
        - Effect: Allow
          Action:
              - lambda:InvokeFunction
          Resource:
              - arn:aws:lambda:us-east-1:*:*
plugins:
    - ./vendor/bref/bref
functions:
    api-1:
        handler: php-api/api-1.php
        description: ""
        timeout: 28
        layers:
            - ${bref:layer.php-74-fpm}
        events:
            - http: ANY /api-1/
            - http: ANY /api-1/{proxy+}
    api-2:
        handler: php-api/api-2.php
        description: ""
        timeout: 28
        layers:
            - ${bref:layer.php-74-fpm}
        events:
            - http: ANY /api-2/
            - http: ANY /api-2/{proxy+}
    api-invoking-api:
        handler: php-api/api-invoking-api.php
        description: ""
        timeout: 28
        layers:
            - ${bref:layer.php-74-fpm}
        events:
            - http: ANY /api-invoking-api/
            - http: ANY /api-invoking-api/{proxy+}
    func-invoking-api:
        handler: php-api/func-invoking-api.php
        description: ""
        timeout: 28
        layers:
            - ${bref:layer.php-74-fpm}
        events:
            - http: ANY /func-invoking-api/
            - http: ANY /func-invoking-api/{proxy+}
    mail-api:
        handler: php-api/mail-api.php
        description: ""
        timeout: 28
        layers:
            - ${bref:layer.php-74-fpm}
        events:
            - http: ANY /mail-api/
            - http: ANY /mail-api/{proxy+}
    api-invoking-func:
        handler: php-func/api-invoking-func.php
        description: ""
        layers:
            - ${bref:layer.php-74}
    func-invoking-func:
        handler: php-func/func-invoking-func.php
        description: ""
        layers:
            - ${bref:layer.php-74}
    index:
        handler: php-func/index.php
        description: ""
        layers:
            - ${bref:layer.php-74}
    mail-func:
        handler: php-func/mail-func.php
        description: ""
        layers:
            - ${bref:layer.php-74}
package:
    exclude:
        - .idea/**
        - node_modules/**
        - tests/**
        - "*.md"
        - "*.js"
        - "**/.DS_Store"
