service: app

provider:
    name: aws
    region: us-east-1
    runtime: provided
    iamRoleStatements:
        - Effect: Allow
          Action:
              - lambda:InvokeFunction
          Resource:
              - arn:aws:lambda:us-east-1:*:*

plugins:
    - ./vendor/bref/bref

functions:
    api-test-1:
        handler: php-api/api-1.php
        description: ''
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        layers:
            - ${bref:layer.php-74-fpm}
        events:
            -   http: 'ANY /1/'
            -   http: 'ANY /1/{proxy+}'

    api-test-2:
        handler: php-api/api-2.php
        description: ''
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        layers:
            - ${bref:layer.php-74-fpm}
        events:
            - http: 'ANY /2/'
            - http: 'ANY /2/{proxy+}'

    mail-api:
        handler: php-api/mail-api.php
        description: ''
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        layers:
            - ${bref:layer.php-74-fpm}
        events:
            - http: 'ANY /email/'
            - http: 'ANY /email/{proxy+}'

    api-invoking-api-test:
        handler: php-api/api-invoking-api.php
        description: ''
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        layers:
            - ${bref:layer.php-74-fpm}
        events:
            - http: 'ANY /api-invoking-api/'
            - http: 'ANY /api-invoking-api/{proxy+}'

    api-invoking-func-test:
        handler: php-func/api-invoking-func.php
        description: ''
        layers:
            - ${bref:layer.php-74}

    func-invoking-api-test:
        handler: php-api/func-invoking-api.php
        description: ''
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        layers:
            - ${bref:layer.php-74-fpm}
        events:
            - http: 'ANY /func-invoking-api/'
            - http: 'ANY /func-invoking-api/{proxy+}'

    func-invoking-func-test:
        handler: php-func/func-invoking-func.php
        description: ''
        layers:
            - ${bref:layer.php-74}

    function-test:
        handler: php-func/index.php
        description: ''
        layers:
            - ${bref:layer.php-74}

    mail-func:
        handler: php-func/mail-func.php
        description: ''
        layers:
            - ${bref:layer.php-74}

# Exclude files from deployment
package:
    exclude:
        - 'node_modules/**'
        - 'tests/**'
        - '*.md'
        - '*.js'
        - '**/.DS_Store'
        - '.idea'
